services:
  backend:
    build:
      context: ./back
    container_name: backend
    ports: ["8000:8000"]
    environment:
      - PYTHONUNBUFFERED=1
      - DISABLE_WARMUP=1         # <- clave: no intentes warmup
    volumes:
      - ./back:/app
      - ./back/db.sqlite3:/app/db.sqlite3
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000 --noreload
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/healthz >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  frontend:
    build:
      context: ./front
    container_name: frontend
    ports: ["3001:3000"]
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run dev -- -p 3001 -H 0.0.0.0
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
