services:
  backend:
    build:
      context: ./back
    container_name: backend
    ports: ["8000:8000"]
    environment:
      - PYTHONUNBUFFERED=1
      - DJ_MIN_PERIODS=3
    volumes:
      - ./back:/app
      - ./back/db.sqlite3:/app/db.sqlite3
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/healthz >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000 --noreload"
    restart: unless-stopped

  frontend:
    build:
      context: ./front
    container_name: frontend
    ports: ["3001:3000"]
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run dev -- -p 3000 -H 0.0.0.0
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_started   # <— no espera health OK
    restart: unless-stopped
