version: "3.9"
services:
  frontend:
    build:
      context: ./front
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
